// Mock Data for Sitesellr Dashboard

export const dashboardStats = {
  totalRevenue: 2847500,
  totalOrders: 1247,
  totalCustomers: 856,
  conversionRate: 3.2,
  revenueChange: 12.5,
  ordersChange: 8.3,
  customersChange: 15.2,
  conversionChange: -2.1,
};

export const revenueData = [
  { month: "Jan", revenue: 185000, orders: 89 },
  { month: "Feb", revenue: 220000, orders: 102 },
  { month: "Mar", revenue: 195000, orders: 95 },
  { month: "Apr", revenue: 280000, orders: 134 },
  { month: "May", revenue: 310000, orders: 156 },
  { month: "Jun", revenue: 350000, orders: 178 },
  { month: "Jul", revenue: 420000, orders: 198 },
  { month: "Aug", revenue: 380000, orders: 185 },
  { month: "Sep", revenue: 290000, orders: 142 },
  { month: "Oct", revenue: 340000, orders: 165 },
  { month: "Nov", revenue: 410000, orders: 195 },
  { month: "Dec", revenue: 467500, orders: 208 },
];

export const salesByCategory = [
  { name: "Electronics", value: 35, color: "#2563EB" },
  { name: "Fashion", value: 28, color: "#10B981" },
  { name: "Home & Living", value: 20, color: "#F59E0B" },
  { name: "Beauty", value: 12, color: "#8B5CF6" },
  { name: "Others", value: 5, color: "#6B7280" },
];

export const products = [
  {
    id: "PRD001",
    name: "Premium Wireless Headphones",
    sku: "WH-PRO-001",
    category: "Electronics",
    price: 4999,
    stock: 156,
    status: "active",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=100&h=100&fit=crop",
    sales: 234,
  },
  {
    id: "PRD002",
    name: "Organic Cotton T-Shirt",
    sku: "TS-ORG-002",
    category: "Fashion",
    price: 899,
    stock: 432,
    status: "active",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=100&h=100&fit=crop",
    sales: 567,
  },
  {
    id: "PRD003",
    name: "Smart Watch Pro",
    sku: "SW-PRO-003",
    category: "Electronics",
    price: 12999,
    stock: 45,
    status: "active",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=100&h=100&fit=crop",
    sales: 189,
  },
  {
    id: "PRD004",
    name: "Minimalist Desk Lamp",
    sku: "DL-MIN-004",
    category: "Home & Living",
    price: 1499,
    stock: 0,
    status: "out_of_stock",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=100&h=100&fit=crop",
    sales: 98,
  },
  {
    id: "PRD005",
    name: "Natural Face Serum",
    sku: "FS-NAT-005",
    category: "Beauty",
    price: 1299,
    stock: 234,
    status: "active",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=100&h=100&fit=crop",
    sales: 445,
  },
  {
    id: "PRD006",
    name: "Leather Wallet",
    sku: "LW-PRE-006",
    category: "Fashion",
    price: 2499,
    stock: 89,
    status: "active",
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=100&h=100&fit=crop",
    sales: 156,
  },
  {
    id: "PRD007",
    name: "Bluetooth Speaker Mini",
    sku: "BS-MIN-007",
    category: "Electronics",
    price: 2999,
    stock: 12,
    status: "low_stock",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=100&h=100&fit=crop",
    sales: 321,
  },
  {
    id: "PRD008",
    name: "Ceramic Plant Pot Set",
    sku: "PP-CER-008",
    category: "Home & Living",
    price: 799,
    stock: 567,
    status: "active",
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=100&h=100&fit=crop",
    sales: 234,
  },
];

export const orders = [
  {
    id: "ORD-2024-001",
    customer: { name: "Rahul Sharma", email: "rahul@example.com", avatar: null },
    items: 3,
    total: 15497,
    status: "delivered",
    paymentStatus: "paid",
    date: "2024-01-15T10:30:00",
    shippingAddress: "123 MG Road, Bangalore, Karnataka 560001",
  },
  {
    id: "ORD-2024-002",
    customer: { name: "Priya Patel", email: "priya@example.com", avatar: null },
    items: 2,
    total: 5898,
    status: "shipped",
    paymentStatus: "paid",
    date: "2024-01-14T14:20:00",
    shippingAddress: "456 Park Street, Mumbai, Maharashtra 400001",
  },
  {
    id: "ORD-2024-003",
    customer: { name: "Amit Kumar", email: "amit@example.com", avatar: null },
    items: 1,
    total: 12999,
    status: "processing",
    paymentStatus: "paid",
    date: "2024-01-14T09:15:00",
    shippingAddress: "789 Anna Salai, Chennai, Tamil Nadu 600002",
  },
  {
    id: "ORD-2024-004",
    customer: { name: "Sneha Reddy", email: "sneha@example.com", avatar: null },
    items: 4,
    total: 8596,
    status: "pending",
    paymentStatus: "pending",
    date: "2024-01-13T16:45:00",
    shippingAddress: "321 Jubilee Hills, Hyderabad, Telangana 500033",
  },
  {
    id: "ORD-2024-005",
    customer: { name: "Vikram Singh", email: "vikram@example.com", avatar: null },
    items: 2,
    total: 3298,
    status: "cancelled",
    paymentStatus: "refunded",
    date: "2024-01-12T11:00:00",
    shippingAddress: "654 Connaught Place, New Delhi 110001",
  },
  {
    id: "ORD-2024-006",
    customer: { name: "Ananya Iyer", email: "ananya@example.com", avatar: null },
    items: 5,
    total: 21495,
    status: "delivered",
    paymentStatus: "paid",
    date: "2024-01-11T13:30:00",
    shippingAddress: "987 Koramangala, Bangalore, Karnataka 560034",
  },
];

export const customers = [
  {
    id: "CUS001",
    name: "Rahul Sharma",
    email: "rahul@example.com",
    phone: "+91 98765 43210",
    orders: 12,
    totalSpent: 89500,
    status: "active",
    joinDate: "2023-06-15",
    segment: "VIP",
  },
  {
    id: "CUS002",
    name: "Priya Patel",
    email: "priya@example.com",
    phone: "+91 87654 32109",
    orders: 8,
    totalSpent: 45200,
    status: "active",
    joinDate: "2023-08-22",
    segment: "Regular",
  },
  {
    id: "CUS003",
    name: "Amit Kumar",
    email: "amit@example.com",
    phone: "+91 76543 21098",
    orders: 3,
    totalSpent: 18900,
    status: "active",
    joinDate: "2023-11-10",
    segment: "New",
  },
  {
    id: "CUS004",
    name: "Sneha Reddy",
    email: "sneha@example.com",
    phone: "+91 65432 10987",
    orders: 15,
    totalSpent: 125000,
    status: "active",
    joinDate: "2023-03-05",
    segment: "VIP",
  },
  {
    id: "CUS005",
    name: "Vikram Singh",
    email: "vikram@example.com",
    phone: "+91 54321 09876",
    orders: 1,
    totalSpent: 3298,
    status: "inactive",
    joinDate: "2024-01-02",
    segment: "New",
  },
];

export const discounts = [
  {
    id: "DISC001",
    code: "WELCOME20",
    type: "percentage",
    value: 20,
    minOrder: 1000,
    maxDiscount: 500,
    usageLimit: 100,
    usedCount: 45,
    status: "active",
    validFrom: "2024-01-01",
    validTo: "2024-03-31",
  },
  {
    id: "DISC002",
    code: "FLAT500",
    type: "fixed",
    value: 500,
    minOrder: 2500,
    maxDiscount: 500,
    usageLimit: 200,
    usedCount: 156,
    status: "active",
    validFrom: "2024-01-01",
    validTo: "2024-02-28",
  },
  {
    id: "DISC003",
    code: "NEWYEAR30",
    type: "percentage",
    value: 30,
    minOrder: 3000,
    maxDiscount: 1000,
    usageLimit: 50,
    usedCount: 50,
    status: "expired",
    validFrom: "2024-01-01",
    validTo: "2024-01-07",
  },
];

export const themes = [
  {
    id: "theme-minimal",
    name: "Minimal",
    description: "Clean, modern design with focus on products",
    preview: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=300&fit=crop",
    category: "Modern",
    isPro: false,
  },
  {
    id: "theme-boutique",
    name: "Boutique",
    description: "Elegant theme for fashion and lifestyle brands",
    preview: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    category: "Fashion",
    isPro: true,
  },
  {
    id: "theme-tech",
    name: "TechStore",
    description: "Bold theme for electronics and gadgets",
    preview: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=400&h=300&fit=crop",
    category: "Electronics",
    isPro: false,
  },
  {
    id: "theme-organic",
    name: "Organic",
    description: "Natural theme for eco-friendly products",
    preview: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400&h=300&fit=crop",
    category: "Lifestyle",
    isPro: true,
  },
  {
    id: "theme-luxe",
    name: "Luxe",
    description: "Premium theme for luxury brands",
    preview: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop",
    category: "Luxury",
    isPro: true,
  },
  {
    id: "theme-starter",
    name: "Starter",
    description: "Simple theme to get started quickly",
    preview: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop",
    category: "Basic",
    isPro: false,
  },
];

export const pricingPlans = [
  {
    id: "basic",
    name: "Basic",
    price: 0,
    period: "Forever Free",
    description: "Perfect for getting started",
    features: [
      "Up to 50 products",
      "2% transaction fee",
      "Basic analytics",
      "Email support",
      "1 staff account",
      "Basic themes",
    ],
    limitations: [
      "No custom domain",
      "Sitesellr branding",
    ],
    cta: "Start Free",
    popular: false,
  },
  {
    id: "pro",
    name: "Pro",
    price: 1999,
    period: "/month",
    description: "For growing businesses",
    features: [
      "Unlimited products",
      "1% transaction fee",
      "Advanced analytics",
      "Priority support",
      "5 staff accounts",
      "All themes",
      "Custom domain",
      "No branding",
      "Abandoned cart recovery",
      "Discount codes",
    ],
    limitations: [],
    cta: "Start 14-day Trial",
    popular: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 7999,
    period: "/month",
    description: "For large scale operations",
    features: [
      "Everything in Pro",
      "0% transaction fee",
      "Dedicated support",
      "Unlimited staff accounts",
      "Custom integrations",
      "API access",
      "White-label solution",
      "Multi-store management",
      "Advanced security",
      "SLA guarantee",
    ],
    limitations: [],
    cta: "Contact Sales",
    popular: false,
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Rajesh Gupta",
    role: "Founder, StyleHub",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh",
    content: "Sitesellr transformed our online business. We went from 100 orders a month to 1000+ within 6 months. The platform is incredibly easy to use.",
    rating: 5,
  },
  {
    id: 2,
    name: "Meera Krishnan",
    role: "CEO, OrganicBasket",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Meera",
    content: "The GST integration and COD support made Sitesellr perfect for the Indian market. Our customers love the smooth checkout experience.",
    rating: 5,
  },
  {
    id: 3,
    name: "Arjun Mehta",
    role: "Owner, TechGadgets",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun",
    content: "Moving from our old platform to Sitesellr was seamless. The analytics dashboard helps us make data-driven decisions every day.",
    rating: 5,
  },
  {
    id: 4,
    name: "Pooja Shah",
    role: "Founder, BeautyBliss",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pooja",
    content: "The themes are beautiful and the drag-drop builder saved us thousands in developer costs. Highly recommend for any D2C brand.",
    rating: 5,
  },
];

export const faqs = [
  {
    question: "How do I get started with Sitesellr?",
    answer: "Simply sign up for a free account, follow our quick setup wizard, add your products, and you're ready to start selling. No technical knowledge required!",
  },
  {
    question: "What payment methods are supported?",
    answer: "We support all major payment gateways including Razorpay, PayU, Paytm, and international options like Stripe. UPI, credit/debit cards, net banking, and COD are all available.",
  },
  {
    question: "Can I use my own domain?",
    answer: "Yes! Pro and Enterprise plans include custom domain support. You can connect your existing domain or purchase a new one through our platform.",
  },
  {
    question: "Is GST invoicing supported?",
    answer: "Absolutely. Sitesellr is built for Indian businesses with full GST support including GSTIN validation, HSN codes, and automatic GST invoice generation.",
  },
  {
    question: "What about shipping integrations?",
    answer: "We integrate with all major Indian couriers including Delhivery, Shiprocket, Bluedart, and more. Automatic pincode serviceability checks and label printing included.",
  },
  {
    question: "Can I migrate from another platform?",
    answer: "Yes, we offer free migration assistance for Pro and Enterprise customers. Our team will help transfer your products, customers, and order history.",
  },
];

export const activityLogs = [
  { id: 1, action: "New order placed", details: "Order #ORD-2024-001 - ₹15,497", time: "2 minutes ago", type: "order" },
  { id: 2, action: "Product updated", details: "Premium Wireless Headphones - Stock updated", time: "15 minutes ago", type: "product" },
  { id: 3, action: "Customer registered", details: "Vikram Singh joined", time: "1 hour ago", type: "customer" },
  { id: 4, action: "Payment received", details: "₹5,898 via Razorpay", time: "2 hours ago", type: "payment" },
  { id: 5, action: "Discount created", details: "WELCOME20 - 20% off", time: "3 hours ago", type: "discount" },
];

export const notifications = [
  { id: 1, title: "New Order", message: "You have a new order #ORD-2024-001", read: false, time: "2 min ago" },
  { id: 2, title: "Low Stock Alert", message: "Bluetooth Speaker Mini is running low", read: false, time: "1 hour ago" },
  { id: 3, title: "Payment Received", message: "₹5,898 payment confirmed", read: true, time: "2 hours ago" },
  { id: 4, title: "Review Received", message: "New 5-star review on Smart Watch Pro", read: true, time: "5 hours ago" },
];
